# frozen_string_literal: true

source "https://rubygems.org"

gem "cucumber", "8.0"
gem "capybara", "3.38"
gem "selenium-webdriver", "4.6.1"
gem "rspec", "3.12"
gem "mongo", "2.17.3"
gem "allure-cucumber", "2.19"
